### ISSUE TITLE
task deployment configurations should be configured from config file 

### ISSUE THREAD

**Issue by wise-east** [isi-nlp/boteval#71]
each customizable item for a task deployment should be configured inside a config file and the frontend should be loaded accordingly 

e.g. 

```yaml
model: 
  type: dropdown
  items: 
    - gpt4
    - gpt3 
number_turns:
  type: slider 
  start: 1
  end: 4 
...
```
